### ISSUE TITLE
guhd crash at restart | Ubuntu  

### ISSUE THREAD

**Issue by Boernsman** [guh/guh#114]
After installing guh and setup the auto-restart, ubuntu encounters a problem at booting. The fault was something about any GPIOs.

**Comment by t-mon** [comment]
I'm taking care of it. Thx
![screen shot 2015-02-19 at 16 41 37](https://cloud.githubusercontent.com/assets/6507449/6272119/a40ae328-b865-11e4-9988-3e7cd4b0db7a.png)

**Comment by t-mon** [comment]
Interessting...

    $ dmesg | grep guhd
    [    7.707794] guhd[1521]: segfault at 3a ip 00007f318af95845 sp 00007fffbd314000 error 4 in libguh.so.1.0.0[7f318af1b000+b5000]

**Comment by t-mon** [comment]
there was an error in the init script. I have tested the init script now and everything is woking fine. closed with pull request #122. please test it on your systems once jenkins builded the packages.
