### ISSUE TITLE
Can't add a Device

### ISSUE THREAD

**Issue by Boernsman** [guh/guh#130]
Add button doesn't work.  After selecting the Channels it is not possible to add the device.
Tried it with Elro and Unitec.

Version: guhd 0.2.0+201502241835~6802ab5~utopic

Request URL: 	http://localhost:3000/api/v1/devices.json
Request Method: 	POST
Status Code: 	HTTP/1.1 500 Internal Server Error
Request Headers 15:55:48.000
User-Agent:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0
Referer:	http://localhost:3000/
Pragma:	no-cache
Host:	localhost:3000
Content-Type:	application/json;charset=utf-8
Content-Length:	1262
Connection:	keep-alive
Cache-Control:	no-cache
Accept-Language:	en-US,en;q=0.5
Accept-Encoding:	gzip, deflate
Accept:	application/json, text/plain, */*

**Comment by t-mon** [comment]
this bug should be moved to [guh-webinterface](https://github.com/guh/guh-webinterface/issues). Please read this article: https://github.com/guh/guh/wiki/Reporting-bugs

**Comment by t-mon** [comment]
Is this bug still relevant? otherwise please close it.
