### ISSUE TITLE
Protocol version in the welcome message changed from Int to String

### ISSUE THREAD

**Issue by wukerplank** [guh/guh#155]
In the latest version of guhd the "protocol version" attribute has changed from int to string. This caused a minor confusion in my JSON parser. I've adapted my code, but I want to make sure it stays that way.

**Comment by t-mon** [comment]
I have not taken that into account... sorry, but it makes sense.
Reason: I moved the API revition into the compiler defines, and not a variable of a class. This will not change in the future. Now the API version and the guh version can be treated equally.

**Comment by t-mon** [comment]
but the api definition is correct...

    "JSONRPC.Version": {
                "description": "Version of this Guh/JSONRPC interface.",
                "params": {},
                "returns": {
                    "protocol version": "String",
                    "version": "String"
                }
            },
