### ISSUE TITLE
snap should bring python runtime

### ISSUE THREAD

**Issue by mzanetti** [guh/guh#190]
Seems the fact that ubuntu core snappy has python preinstalled is more of a coincidence than wanted. In the long run it will probably disappear from the core.

So the guh snap should also include the python engine. "cx-freeze" is a tool that can package up all the dependencies and might be worth looking at for this task.

**Comment by t-mon** [comment]
thx, I'll check it out and build it into the snappy build script

**Comment by t-mon** [comment]
created jenkins job which builds a guh-cli standalone.
