### ISSUE TITLE
Readme.md Pictures 

### ISSUE THREAD

**Issue by Boernsman** [guh/guh#193]
![guh-cli](https://cloud.githubusercontent.com/assets/5207214/8826753/fbd254ec-3088-11e5-9e07-10c3a276de39.png)
![guh-cli devices](https://cloud.githubusercontent.com/assets/5207214/8826760/0cfab5b6-3089-11e5-9012-df0aad571f08.png)
![web interface start screen](https://cloud.githubusercontent.com/assets/5207214/8827351/87b17bd4-308c-11e5-96df-43ba3681fc6c.png)
![web interface add device](https://cloud.githubusercontent.com/assets/5207214/8827355/8bec6326-308c-11e5-80e3-83fdef2a2899.png)
![app sceen ip adress](https://cloud.githubusercontent.com/assets/5207214/8828811/51dc1bec-3094-11e5-8805-b2be415ece97.png)

![app screen rules](https://cloud.githubusercontent.com/assets/5207214/8828873/956c125e-3094-11e5-8970-221f0d8bef89.png)
![app screen devices](https://cloud.githubusercontent.com/assets/5207214/8829159/720dbf0a-3095-11e5-9b80-6c6c9c05dc1a.png)

**Comment by t-mon** [comment]
what is the issue here? :)
