### ISSUE TITLE
osmc (kodi) + guh on raspberry pi: UPNP discovery causes crash of guh-cli

### ISSUE THREAD

**Issue by simonhoenegger** [guh/guh#209]
UPNP multicast does not work between kodi and guh on the raspberry

**Comment by t-mon** [comment]
This problem seems to be the UPnP port 1900 (used from Kodi and guh). I still have to find out how to fix this in the firewall, so that Kodi and guh can join the UDP multicast group.

**Comment by t-mon** [comment]
if guhd and kodi will be started as user, this issue is no longer relevant. If guhd or kodi is running as root, the port can not be shared any more. I have no influence on this behaviour. You'll have to add kodi manually by entering 127.0.0.1 for the IP.
