### ISSUE TITLE
guhd crashes when HUE bridge is not reachable

### ISSUE THREAD

**Issue by Boernsman** [guh/guh#214]
got this result by unplugging the HUE bridge and playing around with one of the HUE lamps on the webinterface.

**Version:**
guhd 0.6.0+201509161929~39f94f7~jessie

**Debug output:**
Connection: "Webserver client 10.0.0.1:56243 connected"
WebServer: "Got valid request from 10.0.0.1:56243"
WebServer: "POST" "/api/v1/devices/{8e31f902-0613-444b-9608-76aab8964771}/execute/{90e91f64-a208-468c-a5a2-7f47e08859e2}"
Rest: Execute action with ParamList (count:1)
     0: Param(Name: "brightness", Value:QVariant(double, 45) )  

WebServer: Async reply finished
WebServer: respond 504 "Gateway Timeout"
PhilipsHue: Refresh Hue Light request error: 0 "Host unreachable"
Rest: Action execution finished with error 14
Segmentation fault

**Comment by t-mon** [comment]
fixed with the timeout fix.
