### ISSUE TITLE
Bad Request when pairing a device

### ISSUE THREAD

**Issue by rhythm-section** [guh/guh#215]
The WebServer responds with a bad request when trying to pair a device. The REST-Interface prompts following error when trying to make an OPTIONS reuqest to /api/v1/devices/pair: Could not parse DeviceId: "pair"

Here is a screenshot of the Request:

![bildschirmfoto 2015-09-21 um 14 09 55](https://cloud.githubusercontent.com/assets/6566718/9991532/0c7a3d2a-606b-11e5-8c14-e843332cc03a.png)

**Comment by t-mon** [comment]
fixed with next update
