### ISSUE TITLE
deviceplugins/commandlauncher: guh has to be started in the foreground (root) to execute everything properly.

### ISSUE THREAD

**Issue by simonhoenegger** [guh/guh#220]
This user-permission problem might lead to misapprehension for non-techies.

**Comment by t-mon** [comment]
This plugin is a developer plugin. If the application was started as daemon (without user id) run the command with following prefix:

    $ su <user> -c <command> 

If you want to run a command as root:

    $ sudo <command>

The user of this plugin has to be familiar with the bash / terminal...

Please close the issue if this works for you.

**Comment by t-mon** [comment]
command launcher moved to `guh-plugins-maker`.
