### ISSUE TITLE
OpenWeatherMap state values after adding device

### ISSUE THREAD

**Issue by rhythm-section** [guh/guh#224]
When adding a OpenWeatherMap device the webinterface has to retrieve the data for the devices states because the states aren't n the response. When retriving the states, all but one of them have a defaultValue (0). The one without defaultValue has a value of null. I think this is a bug.

Furthermore it would be great when the response of the added device already has all states with it so the states have already the right values.

**Comment by t-mon** [comment]
Note: the response of the added device should not contain the states! this was a temporary fix and should be removed as soon as possible!
