### ISSUE TITLE
Retrieved states are missing deviceId

### ISSUE THREAD

**Issue by rhythm-section** [guh/guh#239]
When retrieving state from /devices/{deviceId}/states the API responses with data in the following format:
[
  {
    stateTypeId: {...},
    value: ...
  },
  ...
]

According to the documentation (https://github.com/guh/guh/wiki/REST-API#devices-resource) the API should respond with:

[
    "$ref:State"
]

A state should include a deviceId an so should the response of the API.

**Comment by t-mon** [comment]
according to the JSON-RPC the states list has following format:

    [
        {
            "stateTypeId": "Uuid",
            "value": "Variant"
        }
    ]

so this was basically an error in the REST documantation, which is fixed now.
