### ISSUE TITLE
List of icons

### ISSUE THREAD

**Issue by t-mon** [guh/guh#297]
Following icons will be defined in the guh API as `iconTypes: [ ]`:

- IconBed
- IconBlinds
- IconCeilingLamp
- IconCouch
- IconDeskLamp
- IconDesk
- IconHifi
- IconPower
- IconRadio
- IconSmartPhone
- IconSocket
- IconStandardLamp
- IconSun
- IconTablet
- IconThermometer
- IconTune
- IconTv

**Comment by rhythm-section** [comment]
IconBattery
IconDishwasher
IconWashingMachine
IconLaundryDryer
IconIrHeater
IconSwitch
IconMotionDetector
