### ISSUE TITLE
Plugin Timer needs different resolutions

### ISSUE THREAD

**Issue by t-mon** [guh/guh#299]
A plugin should have the possibility to decide which guhTimer() resolution it needs i.e.:
- every second (i.e. Time plugin)
- every 5 seconds (i.e. Hue plugin syncing)
- every 30 seconds (i.e. WiFi detector)
- every minute
- every 5 minutes
- every 15 minutes (i.e. Weather plugins)
- every 30 minutes
- every hour

**Comment by mzanetti** [comment]
fixed
