### ISSUE TITLE
Additional Unit Types

### ISSUE THREAD

**Issue by Boernsman** [guh/guh#301]
I need for EV Charger, PV Inverters, Batteries etc. additional Unit Types, like: Ampere, Volt, Herz (and the more "exotic" apparent power VA and power reacitve VAr)

**Comment by t-mon** [comment]
can you give me a list with the corresponding units? 

- Amper [A]
- Voltage [V]
- Herz [Hz] or [1/s]
...

**Comment by Boernsman** [comment]
- frequency  - herz [Hz]
- current - ampere [A]
- current - milli ampere [mA]
- voltage - volt [V]
- voltage - milli volt [mV]
- apparent power - volt ampere [VA]
- reactive power - volt ampere reacitve [var] (lower case)
- electrical charge - ampere hour [Ah]
