### ISSUE TITLE
Native Device Protection

### ISSUE THREAD

**Issue by Boernsman** [guh/guh#346]
Some devices need a "protected" or "native" flag, so this device can't be removed or added by the web interface. An example: A consumer device with an embedded temperature senor - the manufactor made a plug-in for the onboard sensors, and ships the devices with the preconfigured plug-in - the consumer should not be able to add, edit or remove those devices.

**Comment by mzanetti** [comment]
I wonder if this shouldn't be done with the "auto" device creation type. Right now, automatically created devices will appear as soon as guh starts up. If the user deletes them, they will reappear on the next restart. This seems a bit broken anyways, so I'm thinking whether we shouldn't change those devices to not be deletable by the user and let the plugin take care of that instead.

@Boernsman @t-mon wdyt?
