### ISSUE TITLE
Bluetooth / Bluez problem at adding Nuimo

### ISSUE THREAD

**Issue by simonhoenegger** [guh/guh#383]
Even a modern Bluetooth Stick is inserted and found from RPi 2 Ubuntu 16.04:

tail -f -n 0 /var/log/syslog
kernel: [ 1127.513778] usb 1-1.4: new full-speed USB device number 5 using dwc_otg
kernel: [ 1127.628120] usb 1-1.4: New USB device found, idVendor=0a12, idProduct=0001
kernel: [ 1127.628149] usb 1-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber=0
kernel: [ 1127.628165] usb 1-1.4: Product: CSR8510 A10
guh systemd[1]: Starting Load/Save RF Kill Switch Status...
guh systemd[1]: Started Load/Save RF Kill Switch Status.
guh systemd[1]: Reached target Bluetooth.

it comes out to this error of the guh application:

Cannot find a running Bluez. Please check the Bluez installation.
 W | Hardware: No Bluetooth device found.

[Important Logs](https://github.com/guh/guh/files/504337/wichtigster.auszug.txt)
[guhd.log](https://github.com/guh/guh/files/504338/guhd.txt)

**Comment by thymjan** [comment]
Had the same issue. Solved this with "sudo apt-get install bluez". It's not on the image you serve for download.

**Comment by t-mon** [comment]
Thanks! I will update the image script!

**Comment by simonhoenegger** [comment]
Installing Bluez solved the problem of course. 
Bluez had been added to dependencies.
