### ISSUE TITLE
Feature request: Arm64 build

### ISSUE THREAD

**Issue by lampi87** [guh/guh#389]
It would be great if you provide arm64 builds

**Comment by t-mon** [comment]
Which os-release and which platform would you need it?

**Comment by lampi87** [comment]
Ubuntu xenial e.g.
Pine64 is arm64 based and cheaper than a RPI :)

**Comment by t-mon** [comment]
Done. In the next few hours there are all guh packages available for `arm64` architecture: 
Ubuntu:
-  `xenial`
-  `wily`
-  `vivid`

Debian:
- `jessie`
