### ISSUE TITLE
Please re-add my name to the copyright holders for the folder debian/

### ISSUE THREAD

**Issue by tijuca** [guh/guh#439]
With commit aad96fa3bf03e49a9c09ea48562289a3e84ab62c my name was removed from the copyright holders for the folder debian/, please see [change from 24 Sep 2016](https://github.com/guh/guh/commit/aad96fa3bf03e49a9c09ea48562289a3e84ab62c#diff-ce1bcec78b4f464111031703889c1e49L17). As far as I remember I haven't give my permission to remove my name nor I was asked to do that.

Please re-add my name and year back to the file debian/copyright file for the debian/ folder.

**Comment by t-mon** [comment]
I rewrote the whole debian folder some time ago, since there were many small errors in your code. I'll re-add you since it could be possible that there are still some lines equal.

**Comment by tijuca** [comment]
Thanks!

> We rewrote the whole debian folder some time ago

Well, the version control tells me something slightly different, there are still a lot references to my contributions in the past and my experience over the past years is it's likely impossible to remove someone over time even indirectly from a project like yours. On the other hand I see no reason why something like that should be done. It's all open source and you have chosen the GPL-[2+,3] (and LGPL-2.1) license for your project. It's some kind of respecting each other and also the four freedoms of the FSF by keeping all the copyright holders over the time together.
